### PR TITLE
data support for GET request

### PR DESCRIPTION
**Pull request by zainengineer**

### CODE REVIEW

**Comment by odino** [comment]
hey @zainengineer, thanks for the PR! Would you be able to cover this case with tests?

cheers

**Comment by zainengineer** [comment]
@odino  thanks for merging. Should I modify https://github.com/namshi/cuzzle/blob/master/tests/Formatter/CurlFormatterTest.php ?

1) Add an assertion that in `testPost()` that it does contain `-d` but not `-G`. 
2) Add a section in ` testGETWithQueryString()` which provides query string using data and assert that output contains both `-d` &&  `-G`

does this sound right?

**Comment by odino** [comment]
Still not merged yet -- we need the tests :) I would say yes, both of them sound good to me

**Comment by zainengineer** [comment]
@odino  
I added assertion for for `testGETWithQueryString()` and in `testPost()`.
Should I rebase and make a new merge request? or is it ok?

**Comment by cirpo** [comment]
@zainengineer thanks for this PR, can you squash it? I'm going to merge it then

**Comment by cirpo** [comment]
@zainengineer, I'm going to squash it

**Comment by odino** [comment]
Done in master

**Comment by odino** [comment]
new tag, `1.2.1`, is out

**Pull request merged**
