### PR TITLE
removed unsupported PHP versions, added latest

### PR DESCRIPTION
**Pull request by cirpo**

### CODE REVIEW

**Review by odracci — APPROVED** [review]

**Review by razanbilwani — APPROVED** [review]

**Comment by geshan** [comment]
Good job @cirpo

**Comment by cirpo** [comment]
Thanks @geshan :D

I guess we need a maintainer here as I can't merge it. @shidhincr can you help?

@odino ? @AyhamAlzoubi? <3

**Comment by weitzman** [comment]
Please, someone help!

**Review by agkloop — APPROVED** [review]

**Comment by weitzman** [comment]
Thanks!! 

PHP8 would be a great next step, if anyone is available.

**Pull request merged**
