### PR TITLE
Migrated to guzzle 6.x

### LINKED ISSUE #8: Support for Guzzle 6.x ?
Hi,

Have you planned to support Guzzle 6.x ?
Looking at [Guzzle Upgrade Guide](https://github.com/guzzle/guzzle/blob/6.0.1/UPGRADING.md), lot of things have changed.

Any idea of time required ?

Thanks,
Regards

### PR DESCRIPTION
**Pull request by csarrazi**
* Integrates Guzzle 6.0
* Bumps the branch alias for `master` 2.0.x-dev.
* Drops support for PHP 5.4 (as Guzzle 6.x only supports 5.5+)

Fixes #8

### CODE REVIEW

**Comment by csarrazi** [comment]
Also, this needs a major version change, as it won't work with legacy versions of Guzzle anymore.

**Comment by csarrazi** [comment]
Ping @odino

**Comment by mmucklo** [comment]
Doesn't this fail in CurlFormatter here (as this class doesn't seem to exist in Guzzle 6, although I could be mistaken):

```php
use GuzzleHttp\Message\RequestInterface;
```

**Comment by odino** [comment]
@csarrazi thanks for this, will be able to have a look at it in the next 2/3 days -- hang tight :)

**Comment by odino** [comment]
thanks man, its in 2.0.0

**Pull request merged**
