### PR TITLE
Don't set fragment with null value

### PR DESCRIPTION
**Pull request by xkobal**
https://github.com/namshi/cuzzle/issues/13

### CODE REVIEW

**Comment by bmancone** [comment]
Thanks @xkobal  !

@odino  (or someone else?), is it good for you ? 
Would be nice to tag 2.0.1 when it's fixed :-)

**Comment by odino** [comment]
:+1: im gonna tag now

**Comment by odino** [comment]
in `2.0.1`

**Comment by bmancone** [comment]
:+1: @odino 

Thanks :-)

**Comment by Tobion** [comment]
The fragment is supposed to be ignored: #15

**Pull request merged**
